Visual refactor
AutomataTheoryEnjoyers/PetShareFrontEnd pull request #11
Opened 2023-04-06 22:45 UTC by MagullOff

2023-04-10 10:37 UTC, JanPalmer commented on src/components/__tests__/announcementListElement.test.tsx
Usunąłeś ten test w końcu?

2023-04-10 10:41 UTC, JanPalmer commented on src/components/announcementListElement.tsx
Poggers to wygląda, ale nie robiłbym tego przesuwania elementu w prawo. Na razie bym zostawił że się podświetla i może marginalnie powiększa, może potem coś zrobimy że np jak się najedzie to się więcej danych pokazuje czy ki chuj. Dziwnie wygląda to przesuwanie w prawo jak lista jest wycentrowana.
Strzałeczka zajebista za to

2023-04-10 10:43 UTC, JanPalmer commented on src/components/applicationListElement.tsx
Super. Skróciłbym trochę czas animacji jak najedziesz na opcje, bo wydaje mi się trochę mało responsywne jak tak z opóźnieniem to wchodzi

2023-04-10 10:46 UTC, JanPalmer commented on src/components/petDetailsElement.tsx
> +  justify-content: space-between;
Może space-around byłby lepszy

2023-04-10 10:46 UTC, JanPalmer commented on src/components/petDetailsElement.tsx
Lil' iffy odnośnie tego że ikonka kota, jako placeholder to może, ale finalnie to dziwnieto będzie wyglądało jak pies a tu kot.
Data urodzenia nie wygląda na wycentrowaną
Na deployu nie ma opisu zwierzaka w danych, trudno powiedzieć jak to będzie wyglądać jak się je doda

2023-04-10 10:47 UTC, JanPalmer commented on src/components/shelterDetails.tsx
> +  justify-content: space-between;
też imo space-around, bo na razie nazwa sheltera i adres są zepchnięte na końce

2023-04-10 10:48 UTC, JanPalmer commented on src/shelter/components/navbar.tsx
ok?

2023-04-10 10:49 UTC, JanPalmer commented on src/shelter/queries/myAnnouncements.ts
Imo na produkcję to można wrzucić wersję z pobieraniem danych z backu

2023-04-10 10:49 UTC, JanPalmer commented on src/shelter/queries/myPets.ts
Na prod raczej wersja z danymi z backendu

2023-04-10 10:50 UTC, JanPalmer commented on src/shelter/router.tsx
> +  width: min(90vw, 1001px);
1001px?

2023-04-10 10:51 UTC, JanPalmer commented on src/shelter/views/announcementDetails/index.tsx
Znacznie więcej linijek zajmują te pliki po tym prettifiy'u XD

2023-04-10 10:53 UTC, JanPalmer commented on src/user/queries/announcements.tsx
Dane na prod z backu?

2023-04-10 10:59 UTC, JanPalmer commented on src/views/pageNotFound/index.tsx
Próbowałeś ImageElement z komponentów? Może by fajniej wyglądało z corner-radiusem to zdjęcie

2023-04-10 11:00 UTC, JanPalmer requested changes
Drobne problemy wizualne, i może dobrze by było żeby deploy na produkcję pobierał dane z backendu

2023-04-10 20:09 UTC, MagullOff commented on src/shelter/queries/myAnnouncements.ts
yeah, ale ona czasem odpierdala, lepiej do testow na razie tak zostawic puki to draft

2023-04-10 20:10 UTC, MagullOff commented on src/shelter/router.tsx
> +  width: min(90vw, 1001px);
baśnie tysiąca i jednej nocy

2023-04-10 20:10 UTC, MagullOff commented on src/shelter/views/announcementDetails/index.tsx
happens, czytelniej i guess

2023-04-10 20:14 UTC, MagullOff commented on src/views/pageNotFound/index.tsx
tam jest troche pod co innego zrobione (z resztą jak patrze to źle trochę) to i tak raczej tymczasowe 404 zostawie jak jest

2023-04-11 08:47 UTC, JanPalmer approved these changes

2023-04-21 08:52 UTC, merged