Draft detali, na razie bez id ogłoszenia
AutomataTheoryEnjoyers/PetShareFrontEnd pull request #7
Opened 2023-03-25 12:54 UTC by JanPalmer

Można je zobaczyć wchodząc w /shelter/announcement-details

2023-03-25 13:01 UTC, JanPalmer commented on src/shelter/router.tsx
> +          <Route path="announcement-details" element={< AnnouncementDetails />} />
w przyszłości ta

2023-03-25 13:03 UTC, JanPalmer commented on src/shelter/views/announcementDetails/index.tsx
> +    height: 500px;
chodziło żeby była jakaś stała wielkość komponentu i obrazek się dostosowywał na wysokość, ale pewnie ta, trzeba będzie coś pomyśleć jak to zrobić.

2023-03-25 13:03 UTC, JanPalmer commented on src/components/announcementDetails.tsx
> +}
że nazwy Container_Date na Container_DateTime?

2023-03-29 18:53 UTC, JanPalmer commented on src/shelter/router.tsx
> +          <Route path="announcement-details" element={< AnnouncementDetails />} />
Teraz jest

2023-03-29 19:09 UTC, MagullOff requested changes
trochę zmian typu code structure/quality

2023-03-29 19:09 UTC, MagullOff commented on src/components/announcementDetails.tsx
> +  var usableApplications = applications.filter((applic) => applic.announcement.id == announcement.id)
nie skracaj nazw zmiennych to nieczytelne, jak coś jest applications po lewej to napisz application po prawej, no i ogólnie skracanie nazw to jest bardzo zła praktyka, po to masz podpowiadarke w VSC żeby pisać nazwy które są zrozumiałe

2023-03-29 19:09 UTC, MagullOff commented on src/components/announcementDetails.tsx
> +export const PetDetailsElement = ({ announcement }: PetProps) => {
te wszystkie elementy i list elementy to zasługują na swój plik ogólnie, zdecydowanie zbyt obciążony jest ten. Masz w głównym src folder components, tam wrzucaj rzeczy które mają oddzielną logikę i są potencjalnie reużywalne, a kafelki typu który jest taki sam dla całej domeny jak najbardziej takie są

2023-03-29 19:09 UTC, MagullOff commented on src/components/announcementDetails.tsx
> +  background-color: red;
kolory typu white, green, red to cringe, są za mocne, weź sobie jakiś lekko lżejszy np `tomato` jest fajny i wrzuć go jako zmienną do globalnych styli i z nich odczytaj. White czasem jest ok ale zwykle też stosuje się jakiś lekki szary bo white jest oczojebny często, sam zadecyduj

2023-03-29 19:09 UTC, MagullOff commented on src/shelter/components/navbar.tsx
> +      <Link name="New Announcement" path="/shelter/new-announcement" />
bruh

2023-03-29 19:09 UTC, MagullOff commented on src/shelter/views/newAnnouncement/index.tsx
> +    <Header>New Announcement</Header>
bruh

2023-03-29 19:09 UTC, MagullOff commented on src/components/announcementDetails.tsx
> +  position: relative;
nie wiem do końca do czego tego używasz ale to position relative brzmi jak kłopoty, moge się mylić

2023-03-31 12:13 UTC, MagullOff approved these changes

2023-03-31 12:13 UTC, MagullOff commented on .github/workflows/react.yml
> +    - run: npm ci
co tu sie dzieje?

2023-03-31 12:15 UTC, JanPalmer commented on .github/workflows/react.yml
> +    - run: npm ci
To była próba dodania instalowania paczki react-icons jak nie chciało się deployować, finalnie plik Workflows się nie zmienił, ogarnąłem że trzeba wrzucać te package.json i już działa

2023-03-31 12:53 UTC, merged